name: Deploy Multi-K8s App

on:
  push:
    branches:
      - main  # Change to your branch if needed

env:
  REGISTRY: docker.io
  CLIENT_IMAGE: ${{ secrets.DOCKER_USERNAME }}/client
  SERVER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/server
  WORKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/worker
  TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push client image
        run: |
          docker build -t $CLIENT_IMAGE:$TAG ./client
          docker push $CLIENT_IMAGE:$TAG

      - name: Build and push server image
        run: |
          docker build -t $SERVER_IMAGE:$TAG ./server
          docker push $SERVER_IMAGE:$TAG

      - name: Build and push worker image
        run: |
          docker build -t $WORKER_IMAGE:$TAG ./worker
          docker push $WORKER_IMAGE:$TAG

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig

      - name: Update image tags in deployments
        run: |
          kubectl set image deployments/client-deployment client=$CLIENT_IMAGE:$TAG -n default
          kubectl set image deployments/server-deployment server=$SERVER_IMAGE:$TAG -n default
          kubectl set image deployments/worker-deployment worker=$WORKER_IMAGE:$TAG -n default
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig

      - name: Apply Kubernetes configs
        run: |
          kubectl apply -f k8s
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig