service:
  type: ClusterIP
  port: 80
  targetPort: 5000 

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

client:
  image:
    repository: shan1500/multi-client
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
    type: ClusterIP

server:
  image:
    repository: shan1500/multi-server
    tag: v3
    pullPolicy: IfNotPresent
  replicas: 3
  env:
    REDIS_HOST: redis-cluster-ip-service
    REDIS_PORT: "6379"
    PGUSER: postgres
    PGHOST: postgres-cluster-ip-service
    PGPORT: "5432"
    PGDATABASE: postgres
    PGPASSWORD_SECRET_NAME: pgpassword
    PGPASSWORD_SECRET_KEY: PGPASSWORD
  service:
    port: 5000
    type: ClusterIP

worker:
  image:
    repository: shan1500/multi-worker
    tag: latest
    pullPolicy: IfNotPresent

redis:
  image: redis
  port: 6379
  serviceType: ClusterIP

postgres:
  image: postgres
  port: 5432
  serviceType: ClusterIP

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: my-app.local
      paths:
        - path: /?(.*)
          pathType: ImplementationSpecific