apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  selector:
    component: postgres
  ports:
    - port: {{ .Values.postgres.port }}
  type: {{ .Values.postgres.serviceType }}
  