{{- if and (hasKey .Values "serviceAccount") (hasKey .Values.serviceAccount "create") (eq .Values.serviceAccount.create true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "my-app.fullname" .) }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
