name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
      
      - name: Enable GKE auth plugin usage
        run: |
          gcloud config set auth/use_gke_gcloud_auth_plugin True

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug GCP_PROJECT_ID and Buildx Tags
        run: |
          echo "Project ID: '${{ secrets.GCP_PROJECT_ID }}'"
          echo "Full command:"
          echo "docker buildx build --platform linux/amd64 --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/multi-client:latest ./client"

      - name: Build and Push Docker Images
        run: |
          docker buildx build --platform linux/amd64 --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/multi-client:latest ./client
          docker buildx build --platform linux/amd64 --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/multi-server:latest ./server
          docker buildx build --platform linux/amd64 --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/multi-worker:latest ./worker

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.28.0

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials multi-cluster-1 \
          --zone northamerica-northeast2-a \
          --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Apply Kubernetes configs
        run: |
          kubectl apply -f ./k8s