name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Images
      run: |
        docker buildx build --platform linux/amd64 --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/multi-client ./client
        docker buildx build --platform linux/amd64 --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/multi-server ./server
        docker buildx build --platform linux/amd64 --push -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/multi-worker ./worker

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.28.0

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials multi-cluster --zone us-central1-c --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Apply Kubernetes configs
      run: |
        kubectl apply -f ./k8s